/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityMini
 */
export interface ActivityMini {
    /**
     * 
     * @type {string}
     * @memberof ActivityMini
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityMini
     */
    startDateLocal?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityMini
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityMini
     */
    name?: string;
}

/**
 * Check if a given object implements the ActivityMini interface.
 */
export function instanceOfActivityMini(value: object): value is ActivityMini {
    return true;
}

export function ActivityMiniFromJSON(json: any): ActivityMini {
    return ActivityMiniFromJSONTyped(json, false);
}

export function ActivityMiniFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityMini {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startDateLocal': json['start_date_local'] == null ? undefined : json['start_date_local'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ActivityMiniToJSON(value?: ActivityMini | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_date_local': value['startDateLocal'],
        'type': value['type'],
        'name': value['name'],
    };
}

