/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityPowerCurve
 */
export interface ActivityPowerCurve {
    /**
     * 
     * @type {string}
     * @memberof ActivityPowerCurve
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityPowerCurve
     */
    startDateLocal?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityPowerCurve
     */
    weight?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivityPowerCurve
     */
    watts?: Array<number>;
}

/**
 * Check if a given object implements the ActivityPowerCurve interface.
 */
export function instanceOfActivityPowerCurve(value: object): value is ActivityPowerCurve {
    return true;
}

export function ActivityPowerCurveFromJSON(json: any): ActivityPowerCurve {
    return ActivityPowerCurveFromJSONTyped(json, false);
}

export function ActivityPowerCurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityPowerCurve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startDateLocal': json['start_date_local'] == null ? undefined : json['start_date_local'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'watts': json['watts'] == null ? undefined : json['watts'],
    };
}

export function ActivityPowerCurveToJSON(value?: ActivityPowerCurve | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_date_local': value['startDateLocal'],
        'weight': value['weight'],
        'watts': value['watts'],
    };
}

