/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityHRCurve
 */
export interface ActivityHRCurve {
    /**
     * 
     * @type {string}
     * @memberof ActivityHRCurve
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityHRCurve
     */
    startDateLocal?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityHRCurve
     */
    weight?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivityHRCurve
     */
    bpm?: Array<number>;
}

/**
 * Check if a given object implements the ActivityHRCurve interface.
 */
export function instanceOfActivityHRCurve(value: object): value is ActivityHRCurve {
    return true;
}

export function ActivityHRCurveFromJSON(json: any): ActivityHRCurve {
    return ActivityHRCurveFromJSONTyped(json, false);
}

export function ActivityHRCurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityHRCurve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startDateLocal': json['start_date_local'] == null ? undefined : json['start_date_local'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'bpm': json['bpm'] == null ? undefined : json['bpm'],
    };
}

export function ActivityHRCurveToJSON(value?: ActivityHRCurve | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_date_local': value['startDateLocal'],
        'weight': value['weight'],
        'bpm': value['bpm'],
    };
}

