/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityPowerCurve } from './ActivityPowerCurve';
import {
    ActivityPowerCurveFromJSON,
    ActivityPowerCurveFromJSONTyped,
    ActivityPowerCurveToJSON,
} from './ActivityPowerCurve';

/**
 * 
 * @export
 * @interface ActivityPowerCurvePayload
 */
export interface ActivityPowerCurvePayload {
    /**
     * 
     * @type {number}
     * @memberof ActivityPowerCurvePayload
     */
    afterKj?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivityPowerCurvePayload
     */
    secs?: Array<number>;
    /**
     * 
     * @type {Array<ActivityPowerCurve>}
     * @memberof ActivityPowerCurvePayload
     */
    curves?: Array<ActivityPowerCurve>;
}

/**
 * Check if a given object implements the ActivityPowerCurvePayload interface.
 */
export function instanceOfActivityPowerCurvePayload(value: object): value is ActivityPowerCurvePayload {
    return true;
}

export function ActivityPowerCurvePayloadFromJSON(json: any): ActivityPowerCurvePayload {
    return ActivityPowerCurvePayloadFromJSONTyped(json, false);
}

export function ActivityPowerCurvePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityPowerCurvePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'afterKj': json['after_kj'] == null ? undefined : json['after_kj'],
        'secs': json['secs'] == null ? undefined : json['secs'],
        'curves': json['curves'] == null ? undefined : ((json['curves'] as Array<any>).map(ActivityPowerCurveFromJSON)),
    };
}

export function ActivityPowerCurvePayloadToJSON(value?: ActivityPowerCurvePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'after_kj': value['afterKj'],
        'secs': value['secs'],
        'curves': value['curves'] == null ? undefined : ((value['curves'] as Array<any>).map(ActivityPowerCurveToJSON)),
    };
}

