/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleteTrainingPlanUpdate
 */
export interface AthleteTrainingPlanUpdate {
    /**
     * 
     * @type {string}
     * @memberof AthleteTrainingPlanUpdate
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof AthleteTrainingPlanUpdate
     */
    trainingPlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof AthleteTrainingPlanUpdate
     */
    trainingPlanStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleteTrainingPlanUpdate
     */
    trainingPlanAlias?: string;
}

/**
 * Check if a given object implements the AthleteTrainingPlanUpdate interface.
 */
export function instanceOfAthleteTrainingPlanUpdate(value: object): value is AthleteTrainingPlanUpdate {
    return true;
}

export function AthleteTrainingPlanUpdateFromJSON(json: any): AthleteTrainingPlanUpdate {
    return AthleteTrainingPlanUpdateFromJSONTyped(json, false);
}

export function AthleteTrainingPlanUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleteTrainingPlanUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'trainingPlanId': json['training_plan_id'] == null ? undefined : json['training_plan_id'],
        'trainingPlanStartDate': json['training_plan_start_date'] == null ? undefined : json['training_plan_start_date'],
        'trainingPlanAlias': json['training_plan_alias'] == null ? undefined : json['training_plan_alias'],
    };
}

export function AthleteTrainingPlanUpdateToJSON(value?: AthleteTrainingPlanUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'training_plan_id': value['trainingPlanId'],
        'training_plan_start_date': value['trainingPlanStartDate'],
        'training_plan_alias': value['trainingPlanAlias'],
    };
}

