/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomItem } from './CustomItem';
import {
    CustomItemFromJSON,
    CustomItemFromJSONTyped,
    CustomItemToJSON,
} from './CustomItem';
import type { Folder } from './Folder';
import {
    FolderFromJSON,
    FolderFromJSONTyped,
    FolderToJSON,
} from './Folder';
import type { AthleteSearchResult } from './AthleteSearchResult';
import {
    AthleteSearchResultFromJSON,
    AthleteSearchResultFromJSONTyped,
    AthleteSearchResultToJSON,
} from './AthleteSearchResult';

/**
 * 
 * @export
 * @interface AthleteProfile
 */
export interface AthleteProfile {
    /**
     * 
     * @type {AthleteSearchResult}
     * @memberof AthleteProfile
     */
    athlete?: AthleteSearchResult;
    /**
     * 
     * @type {Array<Folder>}
     * @memberof AthleteProfile
     */
    sharedFolders?: Array<Folder>;
    /**
     * 
     * @type {Array<CustomItem>}
     * @memberof AthleteProfile
     */
    customItems?: Array<CustomItem>;
}

/**
 * Check if a given object implements the AthleteProfile interface.
 */
export function instanceOfAthleteProfile(value: object): value is AthleteProfile {
    return true;
}

export function AthleteProfileFromJSON(json: any): AthleteProfile {
    return AthleteProfileFromJSONTyped(json, false);
}

export function AthleteProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleteProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'athlete': json['athlete'] == null ? undefined : AthleteSearchResultFromJSON(json['athlete']),
        'sharedFolders': json['sharedFolders'] == null ? undefined : ((json['sharedFolders'] as Array<any>).map(FolderFromJSON)),
        'customItems': json['customItems'] == null ? undefined : ((json['customItems'] as Array<any>).map(CustomItemFromJSON)),
    };
}

export function AthleteProfileToJSON(value?: AthleteProfile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'athlete': AthleteSearchResultToJSON(value['athlete']),
        'sharedFolders': value['sharedFolders'] == null ? undefined : ((value['sharedFolders'] as Array<any>).map(FolderToJSON)),
        'customItems': value['customItems'] == null ? undefined : ((value['customItems'] as Array<any>).map(CustomItemToJSON)),
    };
}

