/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    mimetype?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    url?: string;
}

/**
 * Check if a given object implements the Attachment interface.
 */
export function instanceOfAttachment(value: object): value is Attachment {
    return true;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'mimetype': json['mimetype'] == null ? undefined : json['mimetype'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function AttachmentToJSON(value?: Attachment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'filename': value['filename'],
        'mimetype': value['mimetype'],
        'url': value['url'],
    };
}

