/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bucket
 */
export interface Bucket {
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    secs?: number;
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    movingSecs?: number;
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    watts?: number;
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    hr?: number;
    /**
     * 
     * @type {number}
     * @memberof Bucket
     */
    cadence?: number;
}

/**
 * Check if a given object implements the Bucket interface.
 */
export function instanceOfBucket(value: object): value is Bucket {
    return true;
}

export function BucketFromJSON(json: any): Bucket {
    return BucketFromJSONTyped(json, false);
}

export function BucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bucket {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : json['start'],
        'secs': json['secs'] == null ? undefined : json['secs'],
        'movingSecs': json['movingSecs'] == null ? undefined : json['movingSecs'],
        'watts': json['watts'] == null ? undefined : json['watts'],
        'hr': json['hr'] == null ? undefined : json['hr'],
        'cadence': json['cadence'] == null ? undefined : json['cadence'],
    };
}

export function BucketToJSON(value?: Bucket | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': value['start'],
        'secs': value['secs'],
        'movingSecs': value['movingSecs'],
        'watts': value['watts'],
        'hr': value['hr'],
        'cadence': value['cadence'],
    };
}

