/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Curve
 */
export interface Curve {
    /**
     * 
     * @type {string}
     * @memberof Curve
     */
    id?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Curve
     */
    coefficients?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    r2?: number;
}

/**
 * Check if a given object implements the Curve interface.
 */
export function instanceOfCurve(value: object): value is Curve {
    return true;
}

export function CurveFromJSON(json: any): Curve {
    return CurveFromJSONTyped(json, false);
}

export function CurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): Curve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'coefficients': json['coefficients'] == null ? undefined : json['coefficients'],
        'r2': json['r2'] == null ? undefined : json['r2'],
    };
}

export function CurveToJSON(value?: Curve | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'coefficients': value['coefficients'],
        'r2': value['r2'],
    };
}

