/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataCurve
 */
export interface DataCurve {
    /**
     * 
     * @type {string}
     * @memberof DataCurve
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof DataCurve
     */
    afterKj?: number;
    /**
     * 
     * @type {string}
     * @memberof DataCurve
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof DataCurve
     */
    percentile?: number;
    /**
     * 
     * @type {string}
     * @memberof DataCurve
     */
    startDateLocal?: string;
    /**
     * 
     * @type {string}
     * @memberof DataCurve
     */
    endDateLocal?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataCurve
     */
    secs?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataCurve
     */
    distance?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataCurve
     */
    values?: Array<number>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof DataCurve
     */
    submaxValues?: Array<Array<number>>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof DataCurve
     */
    submaxActivityId?: Array<Array<string>>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataCurve
     */
    startIndex?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataCurve
     */
    endIndex?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataCurve
     */
    activityId?: Array<string>;
}

/**
 * Check if a given object implements the DataCurve interface.
 */
export function instanceOfDataCurve(value: object): value is DataCurve {
    return true;
}

export function DataCurveFromJSON(json: any): DataCurve {
    return DataCurveFromJSONTyped(json, false);
}

export function DataCurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataCurve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'afterKj': json['after_kj'] == null ? undefined : json['after_kj'],
        'label': json['label'] == null ? undefined : json['label'],
        'percentile': json['percentile'] == null ? undefined : json['percentile'],
        'startDateLocal': json['start_date_local'] == null ? undefined : json['start_date_local'],
        'endDateLocal': json['end_date_local'] == null ? undefined : json['end_date_local'],
        'secs': json['secs'] == null ? undefined : json['secs'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'values': json['values'] == null ? undefined : json['values'],
        'submaxValues': json['submax_values'] == null ? undefined : json['submax_values'],
        'submaxActivityId': json['submax_activity_id'] == null ? undefined : json['submax_activity_id'],
        'startIndex': json['start_index'] == null ? undefined : json['start_index'],
        'endIndex': json['end_index'] == null ? undefined : json['end_index'],
        'activityId': json['activity_id'] == null ? undefined : json['activity_id'],
    };
}

export function DataCurveToJSON(value?: DataCurve | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'after_kj': value['afterKj'],
        'label': value['label'],
        'percentile': value['percentile'],
        'start_date_local': value['startDateLocal'],
        'end_date_local': value['endDateLocal'],
        'secs': value['secs'],
        'distance': value['distance'],
        'values': value['values'],
        'submax_values': value['submaxValues'],
        'submax_activity_id': value['submaxActivityId'],
        'start_index': value['startIndex'],
        'end_index': value['endIndex'],
        'activity_id': value['activityId'],
    };
}

