/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteEventsResponse
 */
export interface DeleteEventsResponse {
    /**
     * 
     * @type {number}
     * @memberof DeleteEventsResponse
     */
    eventsDeleted?: number;
}

/**
 * Check if a given object implements the DeleteEventsResponse interface.
 */
export function instanceOfDeleteEventsResponse(value: object): value is DeleteEventsResponse {
    return true;
}

export function DeleteEventsResponseFromJSON(json: any): DeleteEventsResponse {
    return DeleteEventsResponseFromJSONTyped(json, false);
}

export function DeleteEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eventsDeleted': json['eventsDeleted'] == null ? undefined : json['eventsDeleted'],
    };
}

export function DeleteEventsResponseToJSON(value?: DeleteEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'eventsDeleted': value['eventsDeleted'],
    };
}

