/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoomedEvent
 */
export interface DoomedEvent {
    /**
     * 
     * @type {number}
     * @memberof DoomedEvent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DoomedEvent
     */
    externalId?: string;
}

/**
 * Check if a given object implements the DoomedEvent interface.
 */
export function instanceOfDoomedEvent(value: object): value is DoomedEvent {
    return true;
}

export function DoomedEventFromJSON(json: any): DoomedEvent {
    return DoomedEventFromJSONTyped(json, false);
}

export function DoomedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoomedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
    };
}

export function DoomedEventToJSON(value?: DoomedEvent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'external_id': value['externalId'],
    };
}

