/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workout } from './Workout';
import {
    WorkoutFromJSON,
    WorkoutFromJSONTyped,
    WorkoutToJSON,
} from './Workout';
import type { AthleteSearchResult } from './AthleteSearchResult';
import {
    AthleteSearchResultFromJSON,
    AthleteSearchResultFromJSONTyped,
    AthleteSearchResultToJSON,
} from './AthleteSearchResult';

/**
 * 
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    athleteId?: string;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    type?: FolderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    description?: string;
    /**
     * 
     * @type {Array<Workout>}
     * @memberof Folder
     */
    children?: Array<Workout>;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    visibility?: FolderVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    startDateLocal?: string;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    rolloutWeeks?: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    autoRolloutDay?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Folder
     */
    readOnlyWorkouts?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    startingCtl?: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    startingAtl?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Folder
     */
    activityTypes?: Array<FolderActivityTypesEnum>;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    numWorkouts?: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    durationWeeks?: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    hoursPerWeekMin?: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    hoursPerWeekMax?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Folder
     */
    workoutTargets?: Array<FolderWorkoutTargetsEnum>;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    blurb?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Folder
     */
    canEdit?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    sharedWithCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    shareToken?: string;
    /**
     * 
     * @type {AthleteSearchResult}
     * @memberof Folder
     */
    owner?: AthleteSearchResult;
}


/**
 * @export
 */
export const FolderTypeEnum = {
    Folder: 'FOLDER',
    Plan: 'PLAN'
} as const;
export type FolderTypeEnum = typeof FolderTypeEnum[keyof typeof FolderTypeEnum];

/**
 * @export
 */
export const FolderVisibilityEnum = {
    Private: 'PRIVATE',
    Public: 'PUBLIC'
} as const;
export type FolderVisibilityEnum = typeof FolderVisibilityEnum[keyof typeof FolderVisibilityEnum];

/**
 * @export
 */
export const FolderActivityTypesEnum = {
    Ride: 'Ride',
    Run: 'Run',
    Swim: 'Swim',
    WeightTraining: 'WeightTraining',
    Hike: 'Hike',
    Walk: 'Walk',
    AlpineSki: 'AlpineSki',
    BackcountrySki: 'BackcountrySki',
    Badminton: 'Badminton',
    Canoeing: 'Canoeing',
    Crossfit: 'Crossfit',
    EBikeRide: 'EBikeRide',
    EMountainBikeRide: 'EMountainBikeRide',
    Elliptical: 'Elliptical',
    Golf: 'Golf',
    GravelRide: 'GravelRide',
    Handcycle: 'Handcycle',
    HighIntensityIntervalTraining: 'HighIntensityIntervalTraining',
    Hockey: 'Hockey',
    IceSkate: 'IceSkate',
    InlineSkate: 'InlineSkate',
    Kayaking: 'Kayaking',
    Kitesurf: 'Kitesurf',
    MountainBikeRide: 'MountainBikeRide',
    NordicSki: 'NordicSki',
    OpenWaterSwim: 'OpenWaterSwim',
    Padel: 'Padel',
    Pilates: 'Pilates',
    Pickleball: 'Pickleball',
    Racquetball: 'Racquetball',
    Rugby: 'Rugby',
    RockClimbing: 'RockClimbing',
    RollerSki: 'RollerSki',
    Rowing: 'Rowing',
    Sail: 'Sail',
    Skateboard: 'Skateboard',
    Snowboard: 'Snowboard',
    Snowshoe: 'Snowshoe',
    Soccer: 'Soccer',
    Squash: 'Squash',
    StairStepper: 'StairStepper',
    StandUpPaddling: 'StandUpPaddling',
    Surfing: 'Surfing',
    TableTennis: 'TableTennis',
    Tennis: 'Tennis',
    TrailRun: 'TrailRun',
    Transition: 'Transition',
    Velomobile: 'Velomobile',
    VirtualRide: 'VirtualRide',
    VirtualRow: 'VirtualRow',
    VirtualRun: 'VirtualRun',
    WaterSport: 'WaterSport',
    Wheelchair: 'Wheelchair',
    Windsurf: 'Windsurf',
    Workout: 'Workout',
    Yoga: 'Yoga',
    Other: 'Other'
} as const;
export type FolderActivityTypesEnum = typeof FolderActivityTypesEnum[keyof typeof FolderActivityTypesEnum];

/**
 * @export
 */
export const FolderWorkoutTargetsEnum = {
    Auto: 'AUTO',
    Power: 'POWER',
    Hr: 'HR',
    Pace: 'PACE'
} as const;
export type FolderWorkoutTargetsEnum = typeof FolderWorkoutTargetsEnum[keyof typeof FolderWorkoutTargetsEnum];


/**
 * Check if a given object implements the Folder interface.
 */
export function instanceOfFolder(value: object): value is Folder {
    return true;
}

export function FolderFromJSON(json: any): Folder {
    return FolderFromJSONTyped(json, false);
}

export function FolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder {
    if (json == null) {
        return json;
    }
    return {
        
        'athleteId': json['athlete_id'] == null ? undefined : json['athlete_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(WorkoutFromJSON)),
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'startDateLocal': json['start_date_local'] == null ? undefined : json['start_date_local'],
        'rolloutWeeks': json['rollout_weeks'] == null ? undefined : json['rollout_weeks'],
        'autoRolloutDay': json['auto_rollout_day'] == null ? undefined : json['auto_rollout_day'],
        'readOnlyWorkouts': json['read_only_workouts'] == null ? undefined : json['read_only_workouts'],
        'startingCtl': json['starting_ctl'] == null ? undefined : json['starting_ctl'],
        'startingAtl': json['starting_atl'] == null ? undefined : json['starting_atl'],
        'activityTypes': json['activity_types'] == null ? undefined : json['activity_types'],
        'numWorkouts': json['num_workouts'] == null ? undefined : json['num_workouts'],
        'durationWeeks': json['duration_weeks'] == null ? undefined : json['duration_weeks'],
        'hoursPerWeekMin': json['hours_per_week_min'] == null ? undefined : json['hours_per_week_min'],
        'hoursPerWeekMax': json['hours_per_week_max'] == null ? undefined : json['hours_per_week_max'],
        'workoutTargets': json['workout_targets'] == null ? undefined : json['workout_targets'],
        'blurb': json['blurb'] == null ? undefined : json['blurb'],
        'canEdit': json['canEdit'] == null ? undefined : json['canEdit'],
        'sharedWithCount': json['sharedWithCount'] == null ? undefined : json['sharedWithCount'],
        'shareToken': json['shareToken'] == null ? undefined : json['shareToken'],
        'owner': json['owner'] == null ? undefined : AthleteSearchResultFromJSON(json['owner']),
    };
}

export function FolderToJSON(value?: Folder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'athlete_id': value['athleteId'],
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'description': value['description'],
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(WorkoutToJSON)),
        'visibility': value['visibility'],
        'start_date_local': value['startDateLocal'],
        'rollout_weeks': value['rolloutWeeks'],
        'auto_rollout_day': value['autoRolloutDay'],
        'read_only_workouts': value['readOnlyWorkouts'],
        'starting_ctl': value['startingCtl'],
        'starting_atl': value['startingAtl'],
        'activity_types': value['activityTypes'],
        'num_workouts': value['numWorkouts'],
        'duration_weeks': value['durationWeeks'],
        'hours_per_week_min': value['hoursPerWeekMin'],
        'hours_per_week_max': value['hoursPerWeekMax'],
        'workout_targets': value['workoutTargets'],
        'blurb': value['blurb'],
        'canEdit': value['canEdit'],
        'sharedWithCount': value['sharedWithCount'],
        'shareToken': value['shareToken'],
        'owner': AthleteSearchResultToJSON(value['owner']),
    };
}

