/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Activity } from './Activity';
import {
    instanceOfActivity,
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
} from './Activity';
import type { ActivityWithIntervals } from './ActivityWithIntervals';
import {
    instanceOfActivityWithIntervals,
    ActivityWithIntervalsFromJSON,
    ActivityWithIntervalsFromJSONTyped,
    ActivityWithIntervalsToJSON,
} from './ActivityWithIntervals';

/**
 * @type GetActivityDefaultResponse
 * 
 * @export
 */
export type GetActivityDefaultResponse = Activity | ActivityWithIntervals;

export function GetActivityDefaultResponseFromJSON(json: any): GetActivityDefaultResponse {
    return GetActivityDefaultResponseFromJSONTyped(json, false);
}

export function GetActivityDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetActivityDefaultResponse {
    if (json == null) {
        return json;
    }
    if (instanceOfActivity(json)) {
        return ActivityFromJSONTyped(json, true);
    }
    if (instanceOfActivityWithIntervals(json)) {
        return ActivityWithIntervalsFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetActivityDefaultResponseToJSON(value?: GetActivityDefaultResponse | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfActivity(value)) {
        return ActivityToJSON(value as Activity);
    }
    if (instanceOfActivityWithIntervals(value)) {
        return ActivityWithIntervalsToJSON(value as ActivityWithIntervals);
    }

    return {};
}

