/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HRLoadModel
 */
export interface HRLoadModel {
    /**
     * 
     * @type {string}
     * @memberof HRLoadModel
     */
    type?: HRLoadModelTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof HRLoadModel
     */
    icuTrainingLoad?: number;
    /**
     * 
     * @type {number}
     * @memberof HRLoadModel
     */
    trainingDataCount?: number;
}


/**
 * @export
 */
export const HRLoadModelTypeEnum = {
    AvgHr: 'AVG_HR',
    HrZones: 'HR_ZONES',
    Hrss: 'HRSS'
} as const;
export type HRLoadModelTypeEnum = typeof HRLoadModelTypeEnum[keyof typeof HRLoadModelTypeEnum];


/**
 * Check if a given object implements the HRLoadModel interface.
 */
export function instanceOfHRLoadModel(value: object): value is HRLoadModel {
    return true;
}

export function HRLoadModelFromJSON(json: any): HRLoadModel {
    return HRLoadModelFromJSONTyped(json, false);
}

export function HRLoadModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HRLoadModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'icuTrainingLoad': json['icu_training_load'] == null ? undefined : json['icu_training_load'],
        'trainingDataCount': json['trainingDataCount'] == null ? undefined : json['trainingDataCount'],
    };
}

export function HRLoadModelToJSON(value?: HRLoadModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'icu_training_load': value['icuTrainingLoad'],
        'trainingDataCount': value['trainingDataCount'],
    };
}

