/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IcuSegment
 */
export interface IcuSegment {
    /**
     * 
     * @type {number}
     * @memberof IcuSegment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof IcuSegment
     */
    startIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof IcuSegment
     */
    endIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof IcuSegment
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof IcuSegment
     */
    segmentId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IcuSegment
     */
    starred?: boolean;
}

/**
 * Check if a given object implements the IcuSegment interface.
 */
export function instanceOfIcuSegment(value: object): value is IcuSegment {
    return true;
}

export function IcuSegmentFromJSON(json: any): IcuSegment {
    return IcuSegmentFromJSONTyped(json, false);
}

export function IcuSegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): IcuSegment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startIndex': json['start_index'] == null ? undefined : json['start_index'],
        'endIndex': json['end_index'] == null ? undefined : json['end_index'],
        'name': json['name'] == null ? undefined : json['name'],
        'segmentId': json['segment_id'] == null ? undefined : json['segment_id'],
        'starred': json['starred'] == null ? undefined : json['starred'],
    };
}

export function IcuSegmentToJSON(value?: IcuSegment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'start_index': value['startIndex'],
        'end_index': value['endIndex'],
        'name': value['name'],
        'segment_id': value['segmentId'],
        'starred': value['starred'],
    };
}

