/* tslint:disable */
/* eslint-disable */
/**
 * Intervals.icu API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Forecast } from './Forecast';
import {
    ForecastFromJSON,
    ForecastFromJSONTyped,
    ForecastToJSON,
} from './Forecast';

/**
 * 
 * @export
 * @interface WeatherDTO
 */
export interface WeatherDTO {
    /**
     * 
     * @type {Array<Forecast>}
     * @memberof WeatherDTO
     */
    forecasts?: Array<Forecast>;
}

/**
 * Check if a given object implements the WeatherDTO interface.
 */
export function instanceOfWeatherDTO(value: object): value is WeatherDTO {
    return true;
}

export function WeatherDTOFromJSON(json: any): WeatherDTO {
    return WeatherDTOFromJSONTyped(json, false);
}

export function WeatherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'forecasts': json['forecasts'] == null ? undefined : ((json['forecasts'] as Array<any>).map(ForecastFromJSON)),
    };
}

export function WeatherDTOToJSON(value?: WeatherDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'forecasts': value['forecasts'] == null ? undefined : ((value['forecasts'] as Array<any>).map(ForecastToJSON)),
    };
}

